// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TagBlogchangedtoManytoMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TagBlogchangedtoManytoMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201605081700594_Tag-Blog changed to Many-to-Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
