// <auto-generated />
namespace BlogSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedrequiredfieldsfrompostsfollowersandfollowing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedrequiredfieldsfrompostsfollowersandfollowing));
        
        string IMigrationMetadata.Id
        {
            get { return "201605022236081_removed required fields from posts, followers, and following"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
